name: Test1
version: '${project.version}'
main: org.jkadem.test1.Test1
api-version: '1.20'
commands:
  CDStartChunk:
    description: Starts the chunk checker.
    usage: /<command>
  CDStopChunk:
    description: Stops the chunk checker.
    usage: /<command>
  CDSetTimerDuration:
    description: Sets the time required to remove the chunk. Resets all current time on chunk
    usage: /<command> <time (seconds)>