name: Test1
version: '1.0-SNAPSHOT'
main: org.jkadem.test1.Test1
api-version: '1.20'
commands:
  startchunk:
    description: Starts the chunk checker.
  stopchunk:
    description: Stops the chunk checker.